name: Create release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Extract version from fxmanifest
        id: version
        run: |
          VERSION=$(grep "^version" fxmanifest.lua | sed "s/version '\(.*\)'/\1/")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install zip
        run: sudo apt install zip

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install package dependencies
        run: bun install --frozen-lockfile
        working-directory: package

      - name: Install web dependencies
        run: bun install --frozen-lockfile
        working-directory: web

      - name: Run web build script
        run: bun run build
        working-directory: web

      - name: Bundle files
        run: |
          mkdir -p ./temp/ox_lib/web
          cp ./{LICENSE,README.md,fxmanifest.lua,init.lua} ./temp/ox_lib
          cp -r ./{imports,resource,locales} ./temp/ox_lib
          cp -r ./web/build ./temp/ox_lib/web/
          cd ./temp && zip -r ../ox_lib.zip ./ox_lib

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.version.outputs.tag }}
          prerelease: false
          title: ${{ steps.version.outputs.tag }}
          files: ox_lib.zip
